import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log('🌱 Seeding database...')

  // ─── Namirnice ────────────────────────────────────────────────────────────────

  const ingredients = await Promise.all([
    // Meso i riba
    prisma.ingredient.upsert({ where: { name: 'Pileći file' }, update: {}, create: { name: 'Pileći file', unit: 'kg', nationalPrice: 550, category: 'meso' } }),
    prisma.ingredient.upsert({ where: { name: 'Svinjski but' }, update: {}, create: { name: 'Svinjski but', unit: 'kg', nationalPrice: 700, category: 'meso' } }),
    prisma.ingredient.upsert({ where: { name: 'Mljeveno meso (mešano)' }, update: {}, create: { name: 'Mljeveno meso (mešano)', unit: 'kg', nationalPrice: 600, category: 'meso' } }),
    prisma.ingredient.upsert({ where: { name: 'Tunjevina u ulju' }, update: {}, create: { name: 'Tunjevina u ulju', unit: 'kom', nationalPrice: 250, category: 'meso' } }),
    prisma.ingredient.upsert({ where: { name: 'Skuša' }, update: {}, create: { name: 'Skuša', unit: 'kom', nationalPrice: 300, category: 'meso' } }),
    prisma.ingredient.upsert({ where: { name: 'Piletina bataci' }, update: {}, create: { name: 'Piletina bataci', unit: 'kg', nationalPrice: 400, category: 'meso' } }),
    prisma.ingredient.upsert({ where: { name: 'Šunka' }, update: {}, create: { name: 'Šunka', unit: 'kg', nationalPrice: 900, category: 'meso' } }),

    // Mlečni i jaja
    prisma.ingredient.upsert({ where: { name: 'Jaja' }, update: {}, create: { name: 'Jaja', unit: 'kom', nationalPrice: 25, category: 'mlecni' } }),
    prisma.ingredient.upsert({ where: { name: 'Mleko' }, update: {}, create: { name: 'Mleko', unit: 'litar', nationalPrice: 100, category: 'mlecni' } }),
    prisma.ingredient.upsert({ where: { name: 'Jogurt' }, update: {}, create: { name: 'Jogurt', unit: 'kg', nationalPrice: 150, category: 'mlecni' } }),
    prisma.ingredient.upsert({ where: { name: 'Sir mladi' }, update: {}, create: { name: 'Sir mladi', unit: 'kg', nationalPrice: 800, category: 'mlecni' } }),
    prisma.ingredient.upsert({ where: { name: 'Kisela pavlaka' }, update: {}, create: { name: 'Kisela pavlaka', unit: 'kg', nationalPrice: 350, category: 'mlecni' } }),
    prisma.ingredient.upsert({ where: { name: 'Maslac' }, update: {}, create: { name: 'Maslac', unit: 'kg', nationalPrice: 1200, category: 'mlecni' } }),
    prisma.ingredient.upsert({ where: { name: 'Svježi sir' }, update: {}, create: { name: 'Svježi sir', unit: 'kg', nationalPrice: 600, category: 'mlecni' } }),
    prisma.ingredient.upsert({ where: { name: 'Feta sir' }, update: {}, create: { name: 'Feta sir', unit: 'kg', nationalPrice: 1200, category: 'mlecni' } }),

    // Žitarice
    prisma.ingredient.upsert({ where: { name: 'Ovas' }, update: {}, create: { name: 'Ovas', unit: 'kg', nationalPrice: 300, category: 'zitarice' } }),
    prisma.ingredient.upsert({ where: { name: 'Pirinač' }, update: {}, create: { name: 'Pirinač', unit: 'kg', nationalPrice: 250, category: 'zitarice' } }),
    prisma.ingredient.upsert({ where: { name: 'Integralna testenina' }, update: {}, create: { name: 'Integralna testenina', unit: 'kg', nationalPrice: 220, category: 'zitarice' } }),
    prisma.ingredient.upsert({ where: { name: 'Integralni hleb' }, update: {}, create: { name: 'Integralni hleb', unit: 'kom', nationalPrice: 130, category: 'zitarice' } }),
    prisma.ingredient.upsert({ where: { name: 'Pasulj' }, update: {}, create: { name: 'Pasulj', unit: 'kg', nationalPrice: 200, category: 'zitarice' } }),
    prisma.ingredient.upsert({ where: { name: 'Sočivo' }, update: {}, create: { name: 'Sočivo', unit: 'kg', nationalPrice: 350, category: 'zitarice' } }),
    prisma.ingredient.upsert({ where: { name: 'Musli' }, update: {}, create: { name: 'Musli', unit: 'kg', nationalPrice: 500, category: 'zitarice' } }),
    prisma.ingredient.upsert({ where: { name: 'Brašno' }, update: {}, create: { name: 'Brašno', unit: 'kg', nationalPrice: 120, category: 'zitarice' } }),

    // Povrće
    prisma.ingredient.upsert({ where: { name: 'Paradajz' }, update: {}, create: { name: 'Paradajz', unit: 'kg', nationalPrice: 200, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Paprika' }, update: {}, create: { name: 'Paprika', unit: 'kg', nationalPrice: 250, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Krastavac' }, update: {}, create: { name: 'Krastavac', unit: 'kg', nationalPrice: 150, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Spanać' }, update: {}, create: { name: 'Spanać', unit: 'kg', nationalPrice: 300, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Brokoli' }, update: {}, create: { name: 'Brokoli', unit: 'kg', nationalPrice: 350, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Krompir' }, update: {}, create: { name: 'Krompir', unit: 'kg', nationalPrice: 100, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Mrkva' }, update: {}, create: { name: 'Mrkva', unit: 'kg', nationalPrice: 120, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Crni luk' }, update: {}, create: { name: 'Crni luk', unit: 'kg', nationalPrice: 100, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Beli luk' }, update: {}, create: { name: 'Beli luk', unit: 'kom', nationalPrice: 50, category: 'zacini' } }),
    prisma.ingredient.upsert({ where: { name: 'Tikvica' }, update: {}, create: { name: 'Tikvica', unit: 'kg', nationalPrice: 200, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Pečurke' }, update: {}, create: { name: 'Pečurke', unit: 'kg', nationalPrice: 350, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Plavi patlidžan' }, update: {}, create: { name: 'Plavi patlidžan', unit: 'kg', nationalPrice: 200, category: 'povrce' } }),
    prisma.ingredient.upsert({ where: { name: 'Kupus' }, update: {}, create: { name: 'Kupus', unit: 'kg', nationalPrice: 80, category: 'povrce' } }),

    // Voće
    prisma.ingredient.upsert({ where: { name: 'Banana' }, update: {}, create: { name: 'Banana', unit: 'kg', nationalPrice: 200, category: 'ostalo' } }),
    prisma.ingredient.upsert({ where: { name: 'Jabuka' }, update: {}, create: { name: 'Jabuka', unit: 'kg', nationalPrice: 150, category: 'ostalo' } }),
    prisma.ingredient.upsert({ where: { name: 'Limun' }, update: {}, create: { name: 'Limun', unit: 'kom', nationalPrice: 30, category: 'ostalo' } }),

    // Orašasto i ostalo
    prisma.ingredient.upsert({ where: { name: 'Orah' }, update: {}, create: { name: 'Orah', unit: 'kg', nationalPrice: 2500, category: 'ostalo' } }),
    prisma.ingredient.upsert({ where: { name: 'Kikiriki puter' }, update: {}, create: { name: 'Kikiriki puter', unit: 'kg', nationalPrice: 1000, category: 'ostalo' } }),

    // Začini i ulja
    prisma.ingredient.upsert({ where: { name: 'Maslinovo ulje' }, update: {}, create: { name: 'Maslinovo ulje', unit: 'litar', nationalPrice: 1200, category: 'zacini' } }),
    prisma.ingredient.upsert({ where: { name: 'Suncokretovo ulje' }, update: {}, create: { name: 'Suncokretovo ulje', unit: 'litar', nationalPrice: 250, category: 'zacini' } }),
    prisma.ingredient.upsert({ where: { name: 'Med' }, update: {}, create: { name: 'Med', unit: 'kg', nationalPrice: 1500, category: 'ostalo' } }),
    prisma.ingredient.upsert({ where: { name: 'Konzerva paradajza' }, update: {}, create: { name: 'Konzerva paradajza', unit: 'kom', nationalPrice: 120, category: 'povrce' } }),
  ])

  const ing = Object.fromEntries(ingredients.map(i => [i.name, i]))
  console.log(`✅ Kreirano/provereno ${ingredients.length} namirnica`)

  // ─── Recepti ─────────────────────────────────────────────────────────────────

  const recipes = [
    // ── DORUČAK ──────────────────────────────────────────────────────────────
    {
      name: 'Kajgana sa povrćem',
      mealTypes: ['dorucak'],
      prepTime: 10,
      difficulty: 'lako',
      calories: 400,
      protein: 22,
      fat: 30,
      carbs: 10,
      tags: ['brzo', 'visoko_proteinski'],
      steps: [
        'Papriкu i luk iseckati na sitne kockice.',
        'Zagrejati maslinovo ulje na tiganju na srednoj vatri.',
        'Dodati luk i papriкu, dinstati 3 minuta.',
        'Razbiti jaja u tiganj, posoliti i pobiberiti.',
        'Mešati dok se jaja ne stegnu po ukusu.',
        'Servirati toplo.',
      ],
      ingredients: [
        { name: 'Jaja', amount: 3 },
        { name: 'Paprika', amount: 0.1 },
        { name: 'Crni luk', amount: 0.05 },
        { name: 'Maslinovo ulje', amount: 0.015 },
      ],
    },
    {
      name: 'Ovsena kaša sa bananom',
      mealTypes: ['dorucak'],
      prepTime: 10,
      difficulty: 'lako',
      calories: 500,
      protein: 14,
      fat: 8,
      carbs: 88,
      tags: ['brzo', 'veganski'],
      steps: [
        'Mleko sipati u šerpu i zagrejati na srednoj vatri.',
        'Dodati ovas i kuvati uz stalno mešanje 5 minuta.',
        'Ugasiti vatru, dodati med i promešati.',
        'Sipati u zdelicu i prekriti seckanom bananom.',
      ],
      ingredients: [
        { name: 'Ovas', amount: 0.08 },
        { name: 'Mleko', amount: 0.2 },
        { name: 'Banana', amount: 0.15 },
        { name: 'Med', amount: 0.01 },
      ],
    },
    {
      name: 'Tost sa jajima i sirom',
      mealTypes: ['dorucak'],
      prepTime: 15,
      difficulty: 'lako',
      calories: 480,
      protein: 28,
      fat: 26,
      carbs: 36,
      tags: ['brzo', 'visoko_proteinski'],
      steps: [
        'Hleb prepeci u tosteru.',
        'Na maslacu propržiti jaja oko 3 minuta.',
        'Staviti jaja na tost i posuti seckanim sirom.',
        'Posoliti i pobiberiti po ukusu.',
      ],
      ingredients: [
        { name: 'Integralni hleb', amount: 2 },
        { name: 'Jaja', amount: 2 },
        { name: 'Sir mladi', amount: 0.05 },
        { name: 'Maslac', amount: 0.01 },
      ],
    },
    {
      name: 'Omlet sa pečurkama i sirom',
      mealTypes: ['dorucak', 'vecera'],
      prepTime: 15,
      difficulty: 'lako',
      calories: 380,
      protein: 26,
      fat: 28,
      carbs: 6,
      tags: ['brzo', 'visoko_proteinski', 'bez_glutena'],
      steps: [
        'Pečurke iseckati na listiće i propržiti na ulju 4 minuta.',
        'Jaja umutiti viljuškom sa solju i biberom.',
        'Sipati jaja u tiganj i raširiti po pečurkama.',
        'Kad se omlet stegne s jedne strane, posuti sirom i presaviti.',
        'Servirati toplo.',
      ],
      ingredients: [
        { name: 'Jaja', amount: 3 },
        { name: 'Pečurke', amount: 0.1 },
        { name: 'Sir mladi', amount: 0.04 },
        { name: 'Maslinovo ulje', amount: 0.01 },
      ],
    },
    {
      name: 'Musli sa jogurtom i jabukama',
      mealTypes: ['dorucak', 'uzina'],
      prepTime: 5,
      difficulty: 'lako',
      calories: 390,
      protein: 14,
      fat: 10,
      carbs: 60,
      tags: ['brzo', 'veganski'],
      steps: [
        'Jabuku oprati, oljuštiti i iseckati na kockice.',
        'Jogurt sipati u zdelicu.',
        'Dodati musli i jabuku.',
        'Preliti medom i odmah servirati.',
      ],
      ingredients: [
        { name: 'Musli', amount: 0.06 },
        { name: 'Jogurt', amount: 0.15 },
        { name: 'Jabuka', amount: 0.1 },
        { name: 'Med', amount: 0.01 },
      ],
    },
    {
      name: 'Palačinke sa sirom',
      mealTypes: ['dorucak'],
      prepTime: 25,
      difficulty: 'srednje',
      calories: 480,
      protein: 22,
      fat: 16,
      carbs: 60,
      tags: ['porodicni'],
      steps: [
        'Umutiti jaja, mleko i brašno u glatko testo.',
        'Ostaviti testo 10 minuta da odmori.',
        'Na zagrejanom tiganju peći tanke palačinke (1-2 minuta po strani).',
        'Puniti svježi sirom i malo meda.',
        'Presaviti i servirati.',
      ],
      ingredients: [
        { name: 'Brašno', amount: 0.1 },
        { name: 'Jaja', amount: 2 },
        { name: 'Mleko', amount: 0.2 },
        { name: 'Svježi sir', amount: 0.08 },
        { name: 'Med', amount: 0.015 },
      ],
    },
    {
      name: 'Jaja na oko sa šunkom',
      mealTypes: ['dorucak'],
      prepTime: 10,
      difficulty: 'lako',
      calories: 440,
      protein: 32,
      fat: 34,
      carbs: 4,
      tags: ['brzo', 'visoko_proteinski', 'bez_glutena'],
      steps: [
        'Šunku iseckati na kockice i propržiti 1 minut.',
        'Razbiti jaja u tiganj pored šunke.',
        'Peći na tihoj vatri dok se belo ne stegne (oko 3 minuta).',
        'Posoliti i pobiberiti, servirati toplo.',
      ],
      ingredients: [
        { name: 'Jaja', amount: 3 },
        { name: 'Šunka', amount: 0.05 },
        { name: 'Maslac', amount: 0.01 },
      ],
    },
    // ── UŽINA ─────────────────────────────────────────────────────────────────
    {
      name: 'Jogurt sa medom i bananom',
      mealTypes: ['dorucak', 'uzina'],
      prepTime: 5,
      difficulty: 'lako',
      calories: 290,
      protein: 14,
      fat: 5,
      carbs: 48,
      tags: ['brzo', 'veganski', 'bez_glutena'],
      steps: [
        'Jogurt sipati u zdelicu.',
        'Bananu iseckati na kolutove i staviti na jogurt.',
        'Preliti medom po ukusu.',
        'Odmah servirati.',
      ],
      ingredients: [
        { name: 'Jogurt', amount: 0.2 },
        { name: 'Banana', amount: 0.1 },
        { name: 'Med', amount: 0.015 },
      ],
    },
    {
      name: 'Jabuka sa kikiriki puterom',
      mealTypes: ['uzina'],
      prepTime: 5,
      difficulty: 'lako',
      calories: 260,
      protein: 6,
      fat: 10,
      carbs: 38,
      tags: ['brzo', 'veganski', 'bez_glutena'],
      steps: [
        'Jabuku oprati i iseckati na kriške.',
        'Servirati uz kikiriki puter za umakanje.',
      ],
      ingredients: [
        { name: 'Jabuka', amount: 0.2 },
        { name: 'Kikiriki puter', amount: 0.03 },
      ],
    },
    {
      name: 'Svježi sir sa orasima',
      mealTypes: ['uzina', 'dorucak'],
      prepTime: 5,
      difficulty: 'lako',
      calories: 280,
      protein: 18,
      fat: 16,
      carbs: 12,
      tags: ['brzo', 'bez_glutena', 'visoko_proteinski'],
      steps: [
        'Svježi sir staviti u zdelicu.',
        'Orah grubo iseckati i posuti po siru.',
        'Preliti kašičicom meda po ukusu.',
      ],
      ingredients: [
        { name: 'Svježi sir', amount: 0.15 },
        { name: 'Orah', amount: 0.02 },
        { name: 'Med', amount: 0.01 },
      ],
    },
    {
      name: 'Salata od tunjevine',
      mealTypes: ['rucak', 'vecera', 'uzina'],
      prepTime: 10,
      difficulty: 'lako',
      calories: 310,
      protein: 32,
      fat: 14,
      carbs: 10,
      tags: ['brzo', 'visoko_proteinski', 'ekonomican', 'bez_glutena'],
      steps: [
        'Tunjevinu ocediti od ulja i staviti u zdelicu.',
        'Paradajz i krastavac iseckati na kockice.',
        'Pomešati sve sastojke.',
        'Preliti maslinovim uljem i posoliti po ukusu.',
      ],
      ingredients: [
        { name: 'Tunjevina u ulju', amount: 1 },
        { name: 'Paradajz', amount: 0.15 },
        { name: 'Krastavac', amount: 0.1 },
        { name: 'Maslinovo ulje', amount: 0.015 },
      ],
    },
    // ── RUČAK ─────────────────────────────────────────────────────────────────
    {
      name: 'Pileće prsa sa brokolijem',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 30,
      difficulty: 'lako',
      calories: 450,
      protein: 48,
      fat: 16,
      carbs: 20,
      tags: ['visoko_proteinski', 'fit', 'bez_glutena'],
      steps: [
        'Pileće prsa oprati i posušiti papirnim ubrusom.',
        'Posoliti, pobiberiti i premazati maslinovim uljem.',
        'Grilovati na zagrejanom tiganju 6-7 minuta po strani.',
        'Brokoli podeliti na cvetice i blanširati 3 minuta u slanoj vodi.',
        'Beli luk sitno iseckati i propržiti na maslinovom ulju 1 minut.',
        'Dodati brokoli i promešati. Servirati uz piletinu.',
      ],
      ingredients: [
        { name: 'Pileći file', amount: 0.2 },
        { name: 'Brokoli', amount: 0.2 },
        { name: 'Beli luk', amount: 1 },
        { name: 'Maslinovo ulje', amount: 0.02 },
      ],
    },
    {
      name: 'Pileća supa',
      mealTypes: ['rucak'],
      prepTime: 45,
      difficulty: 'srednje',
      calories: 320,
      protein: 30,
      fat: 8,
      carbs: 28,
      tags: ['fit', 'bez_glutena'],
      steps: [
        'Piletinu oprati i staviti u lonac sa 1.5 litra vode.',
        'Dodati celo povrće i zakuvati.',
        'Skidati penu dok se pojavljuje.',
        'Kuvati na tihoj vatri 40 minuta.',
        'Izvaditi piletinu, isčupati meso i vratiti u supu.',
        'Posoliti i pobiberiti. Servirati toplo.',
      ],
      ingredients: [
        { name: 'Pileći file', amount: 0.25 },
        { name: 'Mrkva', amount: 0.1 },
        { name: 'Krompir', amount: 0.15 },
        { name: 'Crni luk', amount: 0.08 },
      ],
    },
    {
      name: 'Špagete bolonjeze',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 40,
      difficulty: 'srednje',
      calories: 680,
      protein: 38,
      fat: 22,
      carbs: 78,
      tags: ['porodicni', 'ekonomican'],
      steps: [
        'Luk i beli luk sitno iseckati i propržiti na ulju 3 minuta.',
        'Dodati mljeveno meso i pržiti uz mešanje dok ne porumeni.',
        'Dodati konzervu paradajza, posoliti, pobiberiti i kuvati 20 minuta.',
        'U slanoj vodi skuvati testeninu al dente.',
        'Sos sipati preko testenine i servirati.',
      ],
      ingredients: [
        { name: 'Integralna testenina', amount: 0.1 },
        { name: 'Mljeveno meso (mešano)', amount: 0.15 },
        { name: 'Konzerva paradajza', amount: 1 },
        { name: 'Crni luk', amount: 0.08 },
        { name: 'Beli luk', amount: 1 },
        { name: 'Suncokretovo ulje', amount: 0.015 },
      ],
    },
    {
      name: 'Pirinač sa piletinom i povrćem',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 35,
      difficulty: 'lako',
      calories: 560,
      protein: 42,
      fat: 12,
      carbs: 68,
      tags: ['fit', 'visoko_proteinski', 'ekonomican'],
      steps: [
        'Pirinač kuvati po uputstvu na pakovanju (oko 18 min).',
        'Piletinu iseckati na kockice i posoliti.',
        'Na ulju propržiti piletinu 5-6 minuta po strani.',
        'Dodati iseckanu papriкu i luk, dinstati još 3 minuta.',
        'Pomešati sa kuvanim pirinčem i servirati.',
      ],
      ingredients: [
        { name: 'Pirinač', amount: 0.08 },
        { name: 'Pileći file', amount: 0.18 },
        { name: 'Paprika', amount: 0.1 },
        { name: 'Crni luk', amount: 0.05 },
        { name: 'Suncokretovo ulje', amount: 0.01 },
      ],
    },
    {
      name: 'Pileća salata sa paradajzom',
      mealTypes: ['rucak', 'vecera', 'uzina'],
      prepTime: 15,
      difficulty: 'lako',
      calories: 340,
      protein: 36,
      fat: 16,
      carbs: 10,
      tags: ['fit', 'brzo', 'bez_glutena', 'visoko_proteinski'],
      steps: [
        'Pileći file iseckati na sitne kockice i propržiti na ulju 6 minuta.',
        'Paradajz i krastavac iseckati na kockice.',
        'Pomešati povrće sa piletinom.',
        'Preliti maslinovim uljem, posoliti i pobiberiti.',
      ],
      ingredients: [
        { name: 'Pileći file', amount: 0.15 },
        { name: 'Paradajz', amount: 0.15 },
        { name: 'Krastavac', amount: 0.1 },
        { name: 'Maslinovo ulje', amount: 0.02 },
      ],
    },
    {
      name: 'Pasulj čorba',
      mealTypes: ['rucak'],
      prepTime: 60,
      difficulty: 'srednje',
      calories: 420,
      protein: 20,
      fat: 8,
      carbs: 64,
      tags: ['srpska_kuhinja', 'veganski', 'ekonomican'],
      steps: [
        'Pasulj potopiti u vodu prethodnu noć.',
        'Ocediti i skuvati u sveže vodi oko 40 minuta.',
        'Na ulju propržiti sitno iseckan luk i mrkvu 5 minuta.',
        'Dodati u pasulj, začiniti solju, biberom i paprikom u prahu.',
        'Kuvati još 15 minuta. Servirati toplo.',
      ],
      ingredients: [
        { name: 'Pasulj', amount: 0.1 },
        { name: 'Crni luk', amount: 0.08 },
        { name: 'Mrkva', amount: 0.08 },
        { name: 'Suncokretovo ulje', amount: 0.015 },
      ],
    },
    {
      name: 'Pileći paprikaš sa pirinčem',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 45,
      difficulty: 'srednje',
      calories: 540,
      protein: 40,
      fat: 14,
      carbs: 60,
      tags: ['srpska_kuhinja', 'porodicni'],
      steps: [
        'Piletinu iseckati na komade i posoliti.',
        'Na ulju propržiti sitno iseckan luk 3-4 minuta.',
        'Dodati piletinu i pržiti 5 minuta da porumeni.',
        'Dodati iseckanu papriкu, paradajz iz konzerve i malo vode.',
        'Kuvati poklopljeno 25 minuta na tihoj vatri.',
        'Servirati uz kuvani pirinač.',
      ],
      ingredients: [
        { name: 'Piletina bataci', amount: 0.25 },
        { name: 'Paprika', amount: 0.15 },
        { name: 'Crni luk', amount: 0.1 },
        { name: 'Konzerva paradajza', amount: 1 },
        { name: 'Pirinač', amount: 0.08 },
        { name: 'Suncokretovo ulje', amount: 0.02 },
      ],
    },
    {
      name: 'Sočivo sa povrćem',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 35,
      difficulty: 'lako',
      calories: 380,
      protein: 22,
      fat: 8,
      carbs: 56,
      tags: ['veganski', 'ekonomican', 'bez_glutena'],
      steps: [
        'Sočivo oprati i potopiti 10 minuta.',
        'Na maslinovom ulju propržiti luk, mrkvu i beli luk 4 minuta.',
        'Dodati sočivo i pokriti vodom (dupla zapremina).',
        'Dodati konzervu paradajza, sol, biber i kurkumu.',
        'Kuvati 20-25 minuta dok sočivo ne omekša.',
        'Servirati toplo, po želji sa limunovim sokom.',
      ],
      ingredients: [
        { name: 'Sočivo', amount: 0.1 },
        { name: 'Mrkva', amount: 0.08 },
        { name: 'Crni luk', amount: 0.08 },
        { name: 'Beli luk', amount: 1 },
        { name: 'Konzerva paradajza', amount: 1 },
        { name: 'Maslinovo ulje', amount: 0.015 },
        { name: 'Limun', amount: 0.5 },
      ],
    },
    {
      name: 'Riba sa krompirom',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 40,
      difficulty: 'srednje',
      calories: 420,
      protein: 34,
      fat: 14,
      carbs: 38,
      tags: ['bez_glutena', 'fit'],
      steps: [
        'Krompir oljuštiti, iseckati na kockice i skuvati 15 minuta.',
        'Skušu oprati, posoliti i pobiberiti.',
        'Na maslinovom ulju pržiti ribu 4 minuta po strani.',
        'Krompir ocediti i začiniti maslinovim uljem i belim lukom.',
        'Servirati ribu uz krompir i krišku limuna.',
      ],
      ingredients: [
        { name: 'Skuša', amount: 1 },
        { name: 'Krompir', amount: 0.2 },
        { name: 'Beli luk', amount: 1 },
        { name: 'Maslinovo ulje', amount: 0.02 },
        { name: 'Limun', amount: 0.5 },
      ],
    },
    {
      name: 'Musaka',
      mealTypes: ['rucak'],
      prepTime: 70,
      difficulty: 'tesko',
      calories: 580,
      protein: 30,
      fat: 32,
      carbs: 44,
      tags: ['srpska_kuhinja', 'porodicni'],
      steps: [
        'Krompir oljuštiti i iseckati na tanke kolutove.',
        'Mljeveno meso propržiti sa lukom dok ne porumeni, začiniti.',
        'U podmazanu posudu za pečenje složiti sloj krompira.',
        'Preliti slojem mljevenog mesa.',
        'Ponoviti i završiti sa slojem krompira.',
        'Preliti mešavinom jaja i kisele pavlake.',
        'Peći u rerni na 180°C oko 45 minuta.',
      ],
      ingredients: [
        { name: 'Krompir', amount: 0.3 },
        { name: 'Mljeveno meso (mešano)', amount: 0.2 },
        { name: 'Crni luk', amount: 0.1 },
        { name: 'Jaja', amount: 2 },
        { name: 'Kisela pavlaka', amount: 0.1 },
        { name: 'Suncokretovo ulje', amount: 0.015 },
      ],
    },
    {
      name: 'Pileći ćevapi sa povrćem',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 30,
      difficulty: 'srednje',
      calories: 520,
      protein: 44,
      fat: 18,
      carbs: 38,
      tags: ['srpska_kuhinja', 'visoko_proteinski'],
      steps: [
        'Mljevenu piletinu izmešati sa soli, biberom i lukom u prahu.',
        'Oblikovati ćevape i ostaviti 15 minuta u frižideru.',
        'Grilovati ćevape 10-12 minuta, okretati svakih 3-4 minuta.',
        'Papriкu i luk iseckati i servirati uz ćevape.',
        'Servirati sa ajvarom ili jogurtom.',
      ],
      ingredients: [
        { name: 'Mljeveno meso (mešano)', amount: 0.2 },
        { name: 'Paprika', amount: 0.15 },
        { name: 'Crni luk', amount: 0.08 },
        { name: 'Suncokretovo ulje', amount: 0.01 },
      ],
    },
    {
      name: 'Pileće prsa u sosu od paradajza',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 35,
      difficulty: 'lako',
      calories: 460,
      protein: 42,
      fat: 16,
      carbs: 34,
      tags: ['fit', 'visoko_proteinski'],
      steps: [
        'Pileće prsa iseckati na veće komade i posoliti.',
        'Na ulju zapečati piletinu 3 minuta po strani.',
        'Dodati sitno iseckan luk i beli luk, propržiti 2 minuta.',
        'Dodati konzervu paradajza i tikvicu iseckanu na kolutove.',
        'Dinstati poklopljeno 20 minuta. Servirati uz pirinač ili hleb.',
      ],
      ingredients: [
        { name: 'Pileći file', amount: 0.2 },
        { name: 'Konzerva paradajza', amount: 1 },
        { name: 'Tikvica', amount: 0.15 },
        { name: 'Crni luk', amount: 0.08 },
        { name: 'Beli luk', amount: 1 },
        { name: 'Maslinovo ulje', amount: 0.015 },
      ],
    },
    // ── VEČERA ────────────────────────────────────────────────────────────────
    {
      name: 'Spanać sa jajima',
      mealTypes: ['dorucak', 'vecera'],
      prepTime: 15,
      difficulty: 'lako',
      calories: 360,
      protein: 24,
      fat: 26,
      carbs: 8,
      tags: ['fit', 'visoko_proteinski', 'bez_glutena'],
      steps: [
        'Beli luk sitno iseckati i propržiti na maslinovom ulju 1 minut.',
        'Dodati oprani spanać i dinstati 3-4 minuta dok ne ovene.',
        'Napraviti udubine i razbiti jaja u spanać.',
        'Poklopiti i kuvati 3-5 minuta dok se belo ne stegne.',
        'Posoliti i pobiberiti. Servirati toplo.',
      ],
      ingredients: [
        { name: 'Spanać', amount: 0.2 },
        { name: 'Jaja', amount: 2 },
        { name: 'Beli luk', amount: 1 },
        { name: 'Maslinovo ulje', amount: 0.015 },
      ],
    },
    {
      name: 'Grčka salata sa feta sirom',
      mealTypes: ['vecera', 'uzina'],
      prepTime: 10,
      difficulty: 'lako',
      calories: 280,
      protein: 10,
      fat: 20,
      carbs: 14,
      tags: ['brzo', 'veganski', 'bez_glutena'],
      steps: [
        'Paradajz, krastavac i papriкu iseckati na veće komade.',
        'Staviti u zdelicu i posuti seckanim crnim lukom.',
        'Preliti maslinovim uljem i limunovim sokom.',
        'Posuti feta sirom i posoliti po ukusu.',
        'Odmah servirati.',
      ],
      ingredients: [
        { name: 'Paradajz', amount: 0.15 },
        { name: 'Krastavac', amount: 0.12 },
        { name: 'Paprika', amount: 0.08 },
        { name: 'Feta sir', amount: 0.05 },
        { name: 'Crni luk', amount: 0.04 },
        { name: 'Maslinovo ulje', amount: 0.02 },
        { name: 'Limun', amount: 0.5 },
      ],
    },
    {
      name: 'Tikvice sa jajima i sirom',
      mealTypes: ['vecera', 'dorucak'],
      prepTime: 20,
      difficulty: 'lako',
      calories: 330,
      protein: 20,
      fat: 24,
      carbs: 10,
      tags: ['brzo', 'bez_glutena', 'fit'],
      steps: [
        'Tikvice iseckati na kolutove, posoliti i ostaviti 5 minuta.',
        'Propržiti tikvice na maslinovom ulju 5-6 minuta.',
        'Razbiti jaja po tikvicama i mešati dok se ne stegnu.',
        'Posuti rendanim sirom i pobiberiti.',
        'Servirati toplo.',
      ],
      ingredients: [
        { name: 'Tikvica', amount: 0.2 },
        { name: 'Jaja', amount: 2 },
        { name: 'Sir mladi', amount: 0.04 },
        { name: 'Maslinovo ulje', amount: 0.015 },
      ],
    },
    {
      name: 'Pileća čorba sa povrćem',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 40,
      difficulty: 'lako',
      calories: 310,
      protein: 26,
      fat: 8,
      carbs: 30,
      tags: ['fit', 'bez_glutena', 'ekonomican'],
      steps: [
        'Piletinu iseckati na kockice i staviti u lonac sa vodom.',
        'Dodati iseckanu mrkvu, krompir i luk.',
        'Zakuvati i skidati penu.',
        'Kuvati na tihoj vatri 30 minuta.',
        'Posoliti i pobiberiti. Dodati sitno iseckan beli luk na kraju.',
      ],
      ingredients: [
        { name: 'Pileći file', amount: 0.18 },
        { name: 'Mrkva', amount: 0.08 },
        { name: 'Krompir', amount: 0.1 },
        { name: 'Crni luk', amount: 0.06 },
        { name: 'Beli luk', amount: 1 },
      ],
    },
    {
      name: 'Musaka od povrća',
      mealTypes: ['rucak', 'vecera'],
      prepTime: 55,
      difficulty: 'srednje',
      calories: 340,
      protein: 14,
      fat: 16,
      carbs: 38,
      tags: ['veganski', 'porodicni'],
      steps: [
        'Plavi patlidžan i tikvice iseckati na kolutove, posoliti i ostaviti 10 minuta.',
        'Krompir iseckati na tanke kolutove.',
        'U podmazanu posudu slagati naizmenično slojeve povrća.',
        'Preliti mešavinom paradajza, belog luka i maslinovog ulja.',
        'Peći u rerni na 190°C 40 minuta.',
      ],
      ingredients: [
        { name: 'Plavi patlidžan', amount: 0.15 },
        { name: 'Tikvica', amount: 0.15 },
        { name: 'Krompir', amount: 0.2 },
        { name: 'Konzerva paradajza', amount: 1 },
        { name: 'Beli luk', amount: 2 },
        { name: 'Maslinovo ulje', amount: 0.02 },
      ],
    },
  ]

  for (const recipeData of recipes) {
    const { ingredients: recipeIngredients, ...data } = recipeData

    const existing = await prisma.recipe.findFirst({ where: { name: data.name } })
    if (existing) {
      console.log(`  ⏭  Recept "${data.name}" već postoji, preskačem`)
      continue
    }

    await prisma.recipe.create({
      data: {
        ...data,
        ingredients: {
          create: recipeIngredients.map(ri => ({
            amount: ri.amount,
            ingredient: { connect: { name: ri.name } },
          })),
        },
      },
    })
    console.log(`  ✅ Kreiran recept: ${data.name}`)
  }

  console.log(`\n🎉 Seed završen!`)
}

main()
  .catch(e => {
    console.error('❌ Seed greška:', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
